# .streamlit/secrets.toml

[connections.snowpark]
account = "account"
user = "user"
password = "password"
role = "role"
warehouse = "warehouse"
database = "database"
schema = "schema"
client_session_keep_alive = true

[private_gsheets_url]

private_gsheets_url = "<Private Google Sheets URL>"

[gcp_service_account]
type = ""
project_id = ""
private_key_id = ""
private_key = ""
client_email = ""
client_id = ""
auth_uri = ""
token_uri = ""
auth_provider_x509_cert_url = ""
client_x509_cert_url = ""
universe_domain = ""